### ISSUE TITLE
Unable to set color scheme

### ISSUE THREAD

**Issue by namitmhatre11** [praveenpuglia/color_scheme_poppins#4]
Error loading colour scheme Packages/User/Poppins.tmTheme: Error parsing plist xml: expected = in file Packages/User/Poppins.tmTheme on line: 34

**Comment by vladyn** [comment]
I think it should be "Packages/User/SublimeLinter/Poppins (SL).tmTheme"

**Comment by praveenpuglia** [comment]
Did you install manually by copying the tmTheme file? Can you try from the **Preferences > Color Scheme** menu option and see if that persists?

**Comment by namitmhatre11** [comment]
I tried to copy "https://github.com/praveenpuglia/color_scheme_poppins/blob/master/Poppins.tmTheme" in "Packages/User/" folder after that I got option under "Preferences--> ColorScheme-->User" to set Poppins color theme which resulted in above error.
also tried @vladyn solution but wont worked.
I've only copied Poppins.tmTheme file; do I need to get any other file?

**Comment by praveenpuglia** [comment]
That's the only file required. Weird! I am gonna check it on a VM and come back to you.

**Comment by praveenpuglia** [comment]
Ok. So I tested it out on new installation of ST3 on Win 7 VM. No problem what so ever. I suggest you delete the tmTheme file and install it via Package Control and give it a try.

Also.
- What version of Sublime are you using?
- Which OS?

**Comment by namitmhatre11** [comment]
I'm checking it on Ubuntu 14.04 with ST3.
Replacing tm file wouldn't fix the issue.

**Comment by praveenpuglia** [comment]
This is so weird. I am on Ubuntu 14.04 as well with ST3. I removed all the files related to poppins and did both manual installation and package control installation. Works for me!

**Comment by namitmhatre11** [comment]
I've updated ST and tried to reconfigure it and that worked!
Really cool color-scheme!
Thanks You!

**Comment by praveenpuglia** [comment]
Glad you like it! :) Thanks!
