### ISSUE TITLE
Which font is used?

### ISSUE THREAD

**Issue by scorypto** [praveenpuglia/color_scheme_poppins#5]
Which font is used in the screenshots?

**Comment by praveenpuglia** [comment]
it's Ahamono. Not so popular and it has less set of glyphs but it does work well. 

https://www.behance.net/gallery/19532783/AhamonoMonospaced

May be I can ask the creator to add more glyohs. :)

**Comment by sureshwilp** [comment]
Thanks a lot for the reply.. This font looks awesome
