### ISSUE TITLE
How do I get the file type icons on the file/folder navigation bar?

### ISSUE THREAD

**Issue by indrayam** [praveenpuglia/color_scheme_poppins#6]
Awesome job! How do I get the cool icons that you have in your screenshot by file type??

**Comment by praveenpuglia** [comment]
Thanks :)

Those icons come from various icon packages. Example - https://github.com/mrmartineau/SetiUI-Icons-Sublime

There are others too. A quick search in package control should find you lot of them  :) 

Closing the issue now. Feel free to reopen it if the problem doesn't get solved. :)
